### ISSUE TITLE
Large number of packets per second

### ISSUE THREAD

**Issue by NofelYaseen** [USNavalResearchLaboratory/mgen#3]
Hi,

I have started two bulk flows:

```
0.0 ON 1 UDP SRC 5001 DST 10.1.1.5/5001 PERIODIC [300000 1024]
0.0 ON 2 UDP SRC 5002 DST 10.1.1.5/5001 POISSON [300000 1024]
```

The network has 25 Gbps capacity, so that is not a problem.
No issue when I used 1/3 number of packets.

I am getting the warning:
Proto Error: ProtoTimerMgr: Warning! real time failure interval:0.000003 (delta:-1.583321)

There is precision time protocol running in the background.

Can anyone please explain why it is happening, how to avoid it and potential impacts of the warning?

Thanks

**Comment by weston-nrl** [comment]
It sounds like your system is unable to generate the number of packets requested -- it's trying, but it's falling behind due to processing constraints, etc. (looking at processor usage will probably show one of your CPU cores running at 100%).  Your receiver will have a bigger problem trying to log each of those packets as you will run into disk IO constraints (though there are ways to avoid that)

For higher datarates, it really helps to increase the size of the packets in addition to the number of packets -- more smaller packets are harder to process than fewer larger packets.  You may have to change link MTUs to allow for larger packets (default is usually 1500 bytes).  MGEN can generate UDP packets up to 8192 bytes currently (increasing that to support larger sizes up to 65K is on our to-do list)

**Comment by NofelYaseen** [comment]
I am more interested in stress testing the network.
I am discarding the packets at the receiver to /dev/null

Thank you for your help, I'll use multiple senders.
